#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ezt a kódot eszköz generálta.
//     Futásidejű verzió:4.0.30319.42000
//
//     Ennek a fájlnak a módosítása helytelen viselkedést eredményezhet, és elvész, ha
//     a kódot újragenerálják.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("autiovis.Resource", IsApplication=true)]

namespace autiovis
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int CatListItemStyle = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int CatListStyle = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int PagerStyle = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int TabStripStyle = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060009
			public const int btnAddPic = 2131099657;
			
			// aapt resource value: 0x7f060000
			public const int card = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int catLayout = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int catList = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int ciLayout = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int imageView1 = 2131099653;
			
			// aapt resource value: 0x7f060001
			public const int img = 2131099649;
			
			// aapt resource value: 0x7f060007
			public const int main = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int pager = 2131099656;
			
			// aapt resource value: 0x7f06000a
			public const int pts = 2131099658;
			
			// aapt resource value: 0x7f060006
			public const int textView1 = 2131099654;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Card = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Categories = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int CategoryItem = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Main = 2130968579;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int autism = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int ttsText = 2131034113;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
